AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - db/schema.rb
    - SCRATCHPAD.rb
Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/LineLength:
  Max: 120
Metrics/AbcSize:
  Max: 20
